### PR TITLE
Add page archiver

### PR DESCRIPTION
**Pull request by ondenman**
Archives scraped pages to github

### CODE REVIEW

**Review by tmtmtmtm — CHANGES_REQUESTED** [review]
screen shot 2016-09-28 at 09 08 47

**Comment by ondenman** [comment]
Updated description.

**Comment by ondenman** [comment]
⚠️ Morph environment needs to be configured

**Comment by tmtmtmtm** [comment]
This page is 404ing. Looks like the new URL is http://house.gov.by/ru/deputies-ru/

**Comment by tmtmtmtm** [comment]
superseded by https://github.com/everypolitician-scrapers/belarus-house-of-representatives-2016

**Pull request closed without merging**
